repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [--autofix, --indent, "4", "--no-sort-keys"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.15
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/python-poetry/poetry
    rev: "1.7.0" # add version here
    hooks:
      - id: poetry-check
      # - id: poetry-lock
      #   args: ["--no-update"]
      - id: poetry-export
        args:
          [
            "-f",
            "requirements.txt",
            "-o",
            "requirements.txt",
            "--only",
            "main",
            "--without-hashes",
          ]


# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
