version: 3

tasks:
  setup:
    desc: ローカル開発環境をセットアップする
    cmds:
      - task: setup:python
      - task: setup:dotenv

  setup:python:
    internal: true
    desc: Python仮想環境をセットアップする
    cmds:
      - uv sync --dev

  setup:dotenv:
    internal: true
    desc: .envファイルを作成する
    preconditions:
      - sh: test ! -f .env
        msg: ".envファイルが既に存在します"
    cmds:
      - cp .env.example .env

  up:
    desc: ローカルのPython仮想環境を使ってBotを起動する
    dotenv: [".env", "{{.ENV}}/.env.", "{{.HOME}}/.env"]
    cmds:
      - uv run main.py

  lint:
    desc: ruffでPythonをLintする
    cmds:
      - uv run ruff check

  lint:fix:
    desc: ruffでPythonをLintし、必要なら自動で修正する
    cmds:
      - uv run ruff check --fix

  fmt:
    desc: ruffでPythonをformatする
    cmds:
      - uv run ruff format

  docker:build:
    desc: Dockerイメージをビルドする
    cmds:
      - docker compose build

  docker:build:nocache:
    desc: Dockerイメージをビルドする (キャッシュは無視される)
    cmds:
      - docker compose build --no-cache

  docker:up:
    desc: Docker環境でBotを起動する
    cmds:
      - docker compose up -d

  docker:down:
    desc: Docker環境を停止する
    cmds:
      - docker compose down

  default:
    desc: ヘルプを表示する
    cmds:
      - task --list-all
