name: Setup Python with uv
description: Setup Python with uv and install dependencies

runs:
  using: composite
  steps:
    - name: Get uv version from mise.toml
      id: uv-version
      shell: bash
      run: echo "uv-version=$(grep -A 1 "\[tools\]" mise.toml | grep "uv" | cut -d'"' -f2)" >> "$GITHUB_OUTPUT"

    - name: Install uv
      uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6 # v6.6.1
      with:
        version: ${{ steps.uv-version.outputs.uv-version }}
        enable-cache: true

    - name: Set up Python
      shell: bash
      run: uv python install

    - name: Install dependencies
      shell: bash
      run: |
        uv sync --dev --frozen
