name: Setup Python with uv
description: Setup Python with uv and install dependencies

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0
      with:
        version-file: .tool-versions
        enable-cache: true
        save-cache: ${{ github.ref == 'refs/heads/main' }}

    - name: Set up Python
      shell: bash
      run: uv python install

    - name: Install dependencies
      shell: bash
      run: |
        uv sync --dev --frozen
