name: check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
        with:
          version: "0.4.17"
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        id: install
        run: |
          uv sync --dev --frozen

      - name: lint
        if: steps.install.outcome == 'success'
        run: |
          uv run ruff check --output-format github .

      - name: check format
        if: steps.install.outcome == 'success'
        run: |
          uv run ruff format --check .
