name: Deploy to ConoHa VPS

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - ".vscode/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CONTAINER_NAME: mikubot

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: setup CPython
        uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          cache: "pip"
          cache-dependency-path: "requirements-dev.lock"
          python-version-file: ".python-version"

      - name: install dependencies
        id: install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.lock

      - name: lint
        if: ${{ always() && steps.install.outcome == 'success' }}
        run: |
          ruff check --output-format github .

      - name: format
        if: ${{ always() && steps.install.outcome == 'success' }}
        run: |
          ruff format --check .

  deploy:
    runs-on: ubuntu-latest

    needs: check
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha, mode=max

      - name: SSH to ConoHa VPS
        uses: appleboy/ssh-action@55dabf81b49d4120609345970c91507e2d734799 # v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          # always remove old container: https://stackoverflow.com/questions/34228864/stop-and-delete-docker-container-if-its-running
          script: |
            echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            docker pull ${{ vars.IMAGE_TAG }}
            docker stop ${{ env.CONTAINER_NAME }} || true && docker rm ${{ env.CONTAINER_NAME }} || true
            docker run \
              -d \
              --name ${{env.CONTAINER_NAME}} \
              --env DISCORD_BOT_TOKEN=${{secrets.DISCORD_TOKEN}} \
              --env LOG_CHANNEL_ID=${{vars.LOG_CHANNEL_ID}} \
              --env NOTION_TOKEN=${{secrets.NOTION_TOKEN}} \
              --env NOTION_DOMAIN=${{vars.NOTION_DOMAIN}} \
              --env SENTRY_DSN=${{secrets.SENTRY_DSN}} \
              ${{ vars.IMAGE_TAG }}
            docker image prune -f
          script_stop: true
