name: Deploy to ConoHa VPS

on:
  push:
    branches:
      - master
    paths-ignore:
      - "legacy/**"
      - "**.md"
      - ".vscode/**"
      - "railway.toml"
      - "renovate.json"
  workflow_dispatch:

env:
  CONTAINER_NAME: mikubot

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ vars.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha, mode=max

      - name: SSH to ConoHa VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          # always remove old container: https://stackoverflow.com/questions/34228864/stop-and-delete-docker-container-if-its-running
          script: |
            echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            docker pull ${{ vars.IMAGE_TAG }}
            docker stop ${{ env.CONTAINER_NAME }} || true && docker rm ${{ env.CONTAINER_NAME }} || true
            docker run \
              -d \
              --name ${{env.CONTAINER_NAME}} \
              --env DISCORD_BOT_TOKEN=${{secrets.DISCORD_TOKEN}} \
              --env LOG_CHANNEL_ID=${{vars.LOG_CHANNEL_ID}} \
              --env NOTION_TOKEN=${{secrets.NOTION_TOKEN}} \
              --env NOTION_DOMAIN=${{vars.NOTION_DOMAIN}} \
              ${{ vars.IMAGE_TAG }}
            docker image prune -f
          script_stop: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
