name: Deploy to ConoHa VPS

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: デプロイする環境 (production | staging)

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  check-input:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - name: Fail if not production or staging
        run: |
          if [[ "${{ inputs.environment }}" != "production" && "${{ inputs.environment }}" != "staging" ]]; then
            echo "::error::Invalid environment: ${{ inputs.environment }}. Skipping deployment."
            exit 1
          fi

  check:
    needs:
      - check-input
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@f94ec6bedd8674c4426838e6b50417d36b6ab231 # v5.3.1
        with:
          version: "0.6.5"
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        id: install
        run: |
          uv sync --dev --frozen

      - name: lint
        if: steps.install.outcome == 'success'
        run: |
          uv run ruff check --output-format github .

      - name: check format
        if: steps.install.outcome == 'success'
        run: |
          uv run ruff format --check .

  build:
    needs:
      - check
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write
    outputs:
      IMAGE_TAG_FOR_PULL: ${{steps.tag.outputs.TAG_FOR_PULL}}

    steps:
      - name: Checkout for production
        if: inputs.environment == 'production'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: master

      - name: Checkout for staging
        if: inputs.environment == 'staging'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: staging

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create image tag
        id: tag
        run: |
          SHA=${{github.sha}}
          TAG="${{vars.IMAGE}}:$(TZ=UTC-9 date +'%Y%m')-${SHA:0:7}"
          echo "TAG_FOR_PULL=${TAG}" >> "$GITHUB_OUTPUT"

          if [ "${{ inputs.environment }}" = "production" ]; then

            LATEST="${{vars.IMAGE}}:latest"
            echo "TAGS=${TAG},${LATEST}" >> "$GITHUB_OUTPUT"

          else
            echo "TAGS=${TAG}" >> "$GITHUB_OUTPUT"
          fi
          echo "Generated image tag: ${TAG}"

      - name: Build and push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.tag.outputs.TAGS }}
          cache-from: type=gha
          cache-to: type=gha, mode=max

  deploy:
    needs:
      - build
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: read
      packages: read

    steps:
      - name: SSH to ConoHa VPS
        uses: appleboy/ssh-action@8faa84277b88b6cd1455986f459aa66cf72bc8a3 # v1.2.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          # always remove old container: https://stackoverflow.com/questions/34228864/stop-and-delete-docker-container-if-its-running
          script: |
            set -euo pipefail
            echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            docker stop ${{ vars.CONTAINER_NAME }} || true && docker rm ${{ vars.CONTAINER_NAME }} || true
            docker run \
              -d \
              --name ${{ vars.CONTAINER_NAME }} \
              --env DISCORD_BOT_TOKEN=${{secrets.DISCORD_BOT_TOKEN}} \
              --env LOG_CHANNEL_ID=${{vars.LOG_CHANNEL_ID}} \
              --env NOTION_TOKEN=${{secrets.NOTION_TOKEN}} \
              --env NOTION_DOMAIN=${{vars.NOTION_DOMAIN}} \
              --env SENTRY_DSN=${{secrets.SENTRY_DSN}} \
              --env DEPLOY_ENV=${{ needs.conoha-setup.outputs.ENVIRONMENT }} \
              --env CF_ACCESS_CLIENT_ID=${{secrets.CF_ACCESS_CLIENT_ID}} \
              --env CF_ACCESS_CLIENT_SECRET=${{secrets.CF_ACCESS_CLIENT_SECRET}} \
              ${{ needs.conoha-build.outputs.IMAGE_TAG_FOR_PULL }}
            docker image prune -f
