name: Docker Image CI

on:
  push:
    branches: ["main", "master"]
    paths-ignore:
      - "legacy/**"
      - "**.md"
      - ".vscode/**"
      - "railway.toml"
      - "renovate.json"
  pull_request:
    branches: ["main", "master"]
    paths-ignore:
      - "legacy/**"
      - "**.md"
      - ".vscode/**"
      - "railway.toml"
      - "renovate.json"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha, mode=max

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
