on:
  push:
    branches:
      - master

name: Build and Deploy a Container
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  SERVICE: discord-bot
  REGION: asia-northeast1
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT }}/discord-bot:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true  # Set to true to authenticate the Cloud Run action

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build . -t ${{ env.IMAGE }} --build-arg token=${{ secrets.DISCORD_TOKEN }} --build-arg apiKey=${{ secrets.TIMETREE2022_APIKEY }}
          docker push ${{ env.IMAGE }}

#       - name: Deploy to Cloud Run
#         id: deploy
#         uses: google-github-actions/deploy-cloudrun@v0.4.0
#         with:
#           service: ${{ env.SERVICE }}
#           image: ${{ env.IMAGE }}
#           region: ${{ env.REGION }}
