name: "pre-commit"

on:
  push:
    branches:
      - master
    paths-ignore:
      - "legacy/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "legacy/**"

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
      - uses: pre-commit/action@v3.0.0
      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
